/* CSV processing is independent of the map and chart. */
(function(root){
function csv(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0];const sep=[';', '\t', ','].sort((a,b)=>first.split(b).length-first.split(a).length)[0];let rows=[],row=[],cell='',quoted=false;
for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Незакрытая кавычка в CSV.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
const num=v=>{if(v==null||String(v).trim()==='')return null;const n=Number(String(v).trim().replace(',','.'));return Number.isFinite(n)?n:null;};
function distance(a,b){const r=Math.PI/180,dl=(b.lat-a.lat)*r,dn=(b.lon-a.lon)*r;const h=Math.sin(dl/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dn/2)**2;return 6371000*2*Math.asin(Math.sqrt(Math.min(1,h)));}
function parse(text){const rows=csv(text);if(rows.length<3)throw Error('Нужны заголовок и минимум две точки.');const headers=rows.shift().map(s=>s.trim().toLowerCase());if(new Set(headers).size!==headers.length)throw Error('Повторяющиеся названия столбцов.');const column=(...names)=>names.map(n=>headers.indexOf(n)).find(i=>i>=0);const lat=column('latitude','lat','широта'),lon=column('longitude','lon','lng','долгота');if(lat===undefined||lon===undefined)throw Error('Не найдены latitude и longitude (широта и долгота).');const elevation=column('elevation_m','elevation','altitude','height','высота');let points=[],cumulative=0,complete=true;
rows.forEach((row,i)=>{if(row.length!==headers.length)throw Error(`Строка ${i+2}: число полей не совпадает с заголовком.`);const p={lat:num(row[lat]),lon:num(row[lon]),id:row[column('point_id')]?.trim()||String(i)};if(p.lat===null||p.lon===null||Math.abs(p.lat)>90||Math.abs(p.lon)>180)throw Error(`Строка ${i+2}: некорректные координаты.`);for(const k of ['elevation_smoothed_m','slope_pct','slope_deg','slope_smoothed_pct','slope_smoothed_deg','elevation_delta_smoothed_m','smoothing_window_m','elevation_delta_m'])p[k]=num(row[column(k)]);p.elevation_m=num(row[elevation]);p.providedDistance=num(row[column('distance_from_start_m')]);const prev=points[i-1];p.segment=prev?distance(prev,p):0;p.distance=prev?prev.distance+p.segment:0;const delta=prev&&prev.elevation_m!==null&&p.elevation_m!==null?p.elevation_m-prev.elevation_m:null;p.elevation_delta_m=p.elevation_delta_m??delta;let pct=p.slope_pct;if(pct===null&&p.slope_deg!==null)pct=Math.tan(p.slope_deg*Math.PI/180)*100;if(pct===null&&delta!==null&&p.segment>0)pct=delta/p.segment*100;p.slope_pct=pct;p.slope_deg=p.slope_deg??(pct===null?null:Math.atan(pct/100)*180/Math.PI);if(p.elevation_m===null|| (i>0&&delta===null))complete=false;if(delta!==null)cumulative+=Math.max(0,delta);p.ascent=complete?cumulative:null;points.push(p);});
const validDistance=points.every((p,i)=>p.providedDistance!==null&&p.providedDistance>=0&&(!i||p.providedDistance>=points[i-1].providedDistance));if(validDistance){const offset=points[0].providedDistance;points.forEach(p=>p.distance=p.providedDistance-offset);}points.forEach((p,i)=>{const prev=points[i-1],ds=prev?p.distance-prev.distance:0;
const dh=prev&&prev.elevation_smoothed_m!==null&&p.elevation_smoothed_m!==null?p.elevation_smoothed_m-prev.elevation_smoothed_m:null;
p.elevation_delta_smoothed_m=p.elevation_delta_smoothed_m??dh;
p.slope_smoothed_pct=p.slope_smoothed_pct??(p.slope_smoothed_deg!==null?Math.tan(p.slope_smoothed_deg*Math.PI/180)*100:dh!==null&&ds>0?100*dh/ds:null);
p.slope_smoothed_deg=p.slope_smoothed_deg??(p.slope_smoothed_pct===null?null:Math.atan(p.slope_smoothed_pct/100)*180/Math.PI);
});if(!complete)points.forEach(p=>p.ascent=null);return points;}
function visibleRange(points,bounds){let start=-1,end=-1;points.forEach((p,i)=>{if(bounds.contains([p.lat,p.lon])){if(start<0)start=i;end=i;}});return [start,end];}
root.RouteData={parse,csv,distance,visibleRange};if(typeof module!=='undefined')module.exports=root.RouteData;
})(typeof window!=='undefined'?window:globalThis);
